// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	rpName: "Captured";
	rpId: "captured.yyin.me";
	rpOrigin: "https://captured.yyin.me";
	secret: string;
	allowCors: string;
	proxyR2: string;
	accountId: string;
	databaseId: string;
	token: string;
	CF_R2_BUCKET: R2Bucket;
	CF_D1_DB: D1Database;
	CF_ASSETS: Fetcher;
}
